### ISSUE TITLE
Wrong flag definition in `brax.training`

### ISSUE THREAD

**Issue by joeryjoery** [google/brax#512]
Fix `flags.DEFINE_integer('policy updates', None, Number of policy updates in APG.')` to have an underscore `flags.DEFINE_integer('policy_updates', None, Number of policy updates in APG.')`, and maybe add a test to check if the entry-point `learn` runs without throwing errors during the build.

See: [brax.training.learner#l124](https://github.com/google/brax/blob/main/brax/training/learner.py#L124)

Error that `absl` raises:

```python
Apptainer> learn
Traceback (most recent call last):
  File "/usr/local/bin/learn", line 4, in <module>
    from brax.training import learner
  File "/usr/local/lib/python3.12/dist-packages/brax/training/learner.py", line 124, in <module>
    flags.DEFINE_integer('policy updates', None,
  File "/usr/local/lib/python3.12/dist-packages/absl/flags/_defines.py", line 672, in DEFINE_integer
    result = DEFINE(
             ^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/absl/flags/_defines.py", line 124, in DEFINE
    return DEFINE_flag(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/absl/flags/_defines.py", line 183, in DEFINE_flag
    fv[flag.name] = flag
    ~~^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/absl/flags/_flagvalues.py", line 439, in __setitem__
    raise _exceptions.Error('Flag name cannot contain a space')
absl.flags._exceptions.Error: Flag name cannot contain a space
```

**Comment by btaba** [comment]
See https://github.com/google/brax/releases/tag/v0.11.0
