### ISSUE TITLE
`learn` not working on Google Cloud TPU

### ISSUE THREAD

**Issue by MandiZhao** [google/brax#65]
On a google cloud tpu vm, I installed jax with 
`pip install "jax[tpu]>=0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html`, then cloned this repo and installed with `pip install -e .`

running `learn` throws the below error:
```

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mandi_zhao/miniconda3/envs/brax/bin/learn", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/mandi_zhao/brax/bin/learn", line 7, in <module>
    app.run(learner.main)
  File "/home/mandi_zhao/miniconda3/envs/brax/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/mandi_zhao/miniconda3/envs/brax/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/mandi_zhao/brax/brax/training/learner.py", line 176, in main
    progress_fn=writer.write_scalars)
  File "/home/mandi_zhao/brax/brax/training/ppo.py", line 465, in train
    (training_state, state), losses = minimize_loop(training_state, state)
  File "/home/mandi_zhao/brax/brax/training/ppo.py", line 402, in _minimize_loop
    length=num_epochs // log_frequency)
  File "/home/mandi_zhao/brax/brax/training/ppo.py", line 387, in run_epoch
    length=num_update_epochs)
  File "/home/mandi_zhao/brax/brax/training/ppo.py", line 361, in minimize_epoch
    length=num_minibatches)
  File "/home/mandi_zhao/brax/brax/training/ppo.py", line 338, in update_model
    loss_grad, metrics = grad_loss(params, data, key_loss)
  File "/home/mandi_zhao/brax/brax/training/ppo.py", line 150, in compute_ppo_loss
    policy_logits, data.actions)
  File "/home/mandi_zhao/brax/brax/training/distribution.py", line 77, in log_prob
    log_probs = dist.log_prob(actions)
  File "/home/mandi_zhao/miniconda3/envs/brax/lib/python3.7/site-packages/tensorflow_probability/substrates/jax/distributions/distribution.py", line 1315, in log_prob
    return self._call_log_prob(value, name, **kwargs)
  File "/home/mandi_zhao/miniconda3/envs/brax/lib/python3.7/site-packages/tensorflow_probability/substrates/jax/distributions/distribution.py", line 1297, in _call_log_prob
    return self._log_prob(value, **kwargs)
  File "/home/mandi_zhao/miniconda3/envs/brax/lib/python3.7/site-packages/tensorflow_probability/substrates/jax/distributions/normal.py", line 190, in _log_prob
    x / scale, self.loc / scale)
  File "/home/mandi_zhao/miniconda3/envs/brax/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 6553, in deferring_binary_op
    return binary_op(self, other)
  File "/home/mandi_zhao/miniconda3/envs/brax/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 839, in true_divide
    return lax.div(x1, x2)
TypeError: div got incompatible shapes for broadcasting: (30, 87), (30, 8).
```

**Comment by erikfrey** [comment]
Closing this issue, but please reach out if you're still hitting this bug.
