### ISSUE TITLE
Silent Rank Promotion on Jitted Fetch Environment

### ISSUE THREAD

**Issue by AlexPiche** [google/brax#82]
Hi,

It looks like the behavior from the environment differ if it is jitted or not. 

```
import jax
from brax import envs
from brax import jumpy as jp
from jax.config import config

config.update('jax_numpy_rank_promotion', 'raise')

env = envs.create(env_name='fetch')
state = env.reset(rng=jp.random_prngkey(seed=0))

for i in range(100):
  action = jp.ones((env.action_size,)) 
  state = env.step(state, action)
    
print('done not jit env')

state = env.reset(rng=jp.random_prngkey(seed=0))
for i in range(100):
  action = jp.ones((env.action_size,)) 
  state = jax.jit(env.step)(state, action)
```

result in the following output:

```
done not jit env
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    state = jax.jit(env.step)(state, action)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/_src/api.py", line 416, in cache_miss
    out_flat = xla.xla_call(
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/core.py", line 1632, in bind
    return call_bind(self, fun, *args, **params)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/core.py", line 1623, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/core.py", line 1635, in process
    return trace.process_call(self, fun, tracers, params)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/core.py", line 627, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/interpreters/xla.py", line 581, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/linear_util.py", line 263, in memoized_fun
    ans = call(fun, *args)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/interpreters/xla.py", line 653, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars,
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/interpreters/xla.py", line 665, in lower_xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1542, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1520, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/brax/envs/wrappers.py", line 87, in step
    state = self.env.step(state, action)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/brax/envs/wrappers.py", line 61, in step
    state = self.env.step(state, action)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/brax/envs/fetch.py", line 55, in step
    obs = self._get_obs(qp, info)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/brax/envs/fetch.py", line 104, in _get_obs
    pos_local = qp.pos - qp.pos[self.torso_idx]
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/core.py", line 518, in __sub__
    def __sub__(self, other): return self.aval._sub(self, other)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 6589, in deferring_binary_op
    return binary_op(self, other)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/_src/api.py", line 416, in cache_miss
    out_flat = xla.xla_call(
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/core.py", line 1632, in bind
    return call_bind(self, fun, *args, **params)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/core.py", line 1623, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/core.py", line 1635, in process
    return trace.process_call(self, fun, tracers, params)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1330, in process_call
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(f, self.main, in_avals)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1520, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 679, in <lambda>
    fn = lambda x1, x2: lax_fn(*_promote_args(numpy_fn.__name__, x1, x2))
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 581, in _promote_args
    return _promote_shapes(fun_name, *_promote_dtypes(*args))
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 499, in _promote_shapes
    _rank_promotion_warning_or_error(fun_name, shapes)
  File "/Users/alexandre.piche/Code/bayes_bsuite/jax_env/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 516, in _rank_promotion_warning_or_error
    raise ValueError(msg.format(fun_name, ' '.join(map(str, shapes))))
jax._src.traceback_util.UnfilteredStackTrace: ValueError: Operands could not be broadcast together for subtract on shapes (13, 3) (3,) and with the config option jax_numpy_rank_promotion='raise'. For more information, see https://jax.readthedocs.io/en/latest/rank_promotion_warning.html.
```

Best,

Alex

**Comment by erikfrey** [comment]
Closing this as I think it's addressed, but please do re-open if you have any remaining questions.
